home/urls.py
from django.urls import path

from .views import *
from .apiViews import *
#
# app_name = 'polls'
urlpatterns = [
    path('login/', loginPage, name='loginPage'),
    path('', dashboard, name='dashboard'),
    path('index', index, name='index'),
    path('postLogin/', postLogin, name='postLogin'),
    path('logout/', user_logout, name='logout'),

    path('new_deposit/', new_deposit, name='new_deposit'),
    path('edit_deposit/<int:id>/', edit_deposit, name='edit_deposit'),
    path('deposit_history/', deposit_history, name='deposit_history'),
    path('deposit_detail/<int:id>/', deposit_detail, name='deposit_detail'),
    path('edit_deposit_detail/<int:id>/', edit_deposit_detail, name='edit_deposit_detail'),
    path('backup/', backup, name='backup'),
    path('download_backup/', download_backup, name='download_backup'),
    path('daily_flow/', daily_report, name='daily_report'),

    path('print_billA5/', print_billA5, name='print_billA5'),
    path('print_billA4/', print_billA4, name='print_billA4'),
    path('with_print_billA5/', with_print_billA5, name='with_print_billA5'),
    path('with_print_billA4/', with_print_billA4, name='with_print_billA4'),

    # API
    path('api/deposit_post/', deposit_post, name='deposit_post'),
    path('api/edit_deposit_post/', edit_deposit_post, name='edit_deposit_post'),
    path('api/IncompleteDepositListJson/', IncompleteDepositListJson.as_view(), name='IncompleteDepositListJson'),
    path('api/PartiallyCompletedDepositListJson/', PartiallyCompletedDepositListJson.as_view(),
         name='PartiallyCompletedDepositListJson'),
    path('api/CompletedDepositListJson/', CompletedDepositListJson.as_view(), name='CompletedDepositListJson'),

    path('api/CashBookDebitListJson/', CashBookDebitListJson.as_view(), name='CashBookDebitListJson'),
    path('api/CashBookCreditListJson/', CashBookCreditListJson.as_view(), name='CashBookCreditListJson'),

    path('api/delete_deposit/', delete_deposit, name='delete_deposit'),
    path('api/search_deposit/', search_deposit, name='search_deposit'),
    path('api/get_deposit_detail/<int:id>/', get_deposit_detail, name='get_deposit_detail'),
    path('api/item_closing_post/', item_closing_post, name='item_closing_post'),
    path('api/item_closing_edit_post/', item_closing_edit_post, name='item_closing_edit_post'),

    path('api/inflow_post/', inflow_post, name='inflow_post'),
    path('api/outflow_post/', outflow_post, name='outflow_post'),

    path('api/get_customer_list/', get_customer_list, name='get_customer_list'),
    path('api/GetCustomerDetailByName/', get_customer_detail_by_name, name='GetCustomerDetailByName'),


    path('api/get_item_list/', get_item_list, name='get_item_list'),
    path('api/get_item_detail_by_name/', get_item_detail_by_name, name='get_item_detail_by_name'),

    path('api/take_interest_post/', take_interest_post, name='take_interest_post'),
    path('api/edit_interest_post/', edit_interest_post, name='edit_interest_post'),
    path('api/get_deposits_search/', get_deposits_search, name='get_deposits_search'),
    path('api/delete_interest_post/', delete_interest_post, name='delete_interest_post'),
    path('api/delete_cashbook_entry/', delete_cashbook_entry, name='delete_cashbook_entry'),
    path('api/edit_cashbook_post/', edit_cashbook_post, name='edit_cashbook_post'),
    path('api/get_today_cashbook_balance/', get_today_cashbook_balance, name='get_today_cashbook_balance'),

    # customer List
    path('customers_list/', customers_list, name='customers_list'),
    path('api/CustomerListJson/', CustomerListJson.as_view(), name='CustomerListJson'),
    path('api/delete_customer/', delete_customer, name='delete_customer'),
    path('api/get_customer_detail/<int:pk>/', get_customer_detail, name='get_customer_detail'),
    path('api/update_customer_detail/', update_customer_detail, name='update_customer_detail'),
    path('api/add_customer_detail/', add_customer_detail, name='add_customer_detail'),



    ]

shiroiPro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('activate/', include(('activation.urls', 'activation'), namespace='activationApp')),
    path('', include(('home.urls', 'home'), namespace='homeApp')),
    path('admin/', admin.site.urls),
    path('', include('pwa.urls')),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/views.py
import sys
from datetime import datetime

from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.core import management

# Create your views here.
# Create your views here.
from activation.models import Validity
from activation.views import is_activated
from home.numberToWord import num2words
from .models import *


def dashboard(request):
    if request.user.is_authenticated:
        try:
            val = Validity.objects.last()
            message = "Your License is Valid till {}".format(val.expiryDate.strftime('%d-%m-%Y'))
        except:
            message = "You are using a trial version."

        context = {
            'message': message
        }

        return render(request, 'home/dashboard.html', context)
    else:
        return redirect('homeApp:loginPage')


@is_activated()
def index(request):
    if request.user.is_authenticated:
        return render(request, 'home/index.html')
    else:
        return redirect('homeApp:loginPage')


def loginPage(request):
    if not request.user.is_authenticated:
        return render(request, 'home/login.html')
    else:
        return redirect('homeApp:dashboard')


@is_activated()
def new_deposit(request):
    if request.user.is_authenticated:
        depo = Deposit.objects.filter(isDeleted=False).count()
        depo = 'SS' + str(depo + 1).zfill(5)

        context = {
            'ID': depo
        }
        return render(request, 'home/newDepost.html', context)
    else:
        return redirect('homeApp:loginPage')


@is_activated()
def edit_deposit(request, id=None):
    if request.user.is_authenticated:
        instance = get_object_or_404(Deposit, pk = int(id))
        items = DepositItem.objects.filter(depositID_id = instance.pk)
        interests = Interest.objects.filter(depositID_id=instance.pk, isDeleted=False)

        context = {
            'instance': instance,
            'items': items,
            'interests': interests
        }
        return render(request, 'home/editDepost.html', context)
    else:
        return redirect('homeApp:loginPage')


@is_activated()
def deposit_history(request):
    if request.user.is_authenticated:
        return render(request, 'home/depositHistory.html')
    else:
        return redirect('homeApp:loginPage')

@is_activated()
def backup(request):
    if request.user.is_authenticated:
        return render(request, 'home/backup.html')
    else:
        return redirect('homeApp:loginPage')




@is_activated()
def deposit_detail(request, id=None):
    if request.user.is_authenticated:
        instance = get_object_or_404(Deposit, id=int(id))
        items = DepositItem.objects.filter(depositID_id=instance.pk)
        all_in = Interest.objects.filter(depositID_id=int(id))
        if instance.actionType == 'interest':
            instance_new = get_object_or_404(Deposit, depositSerialID=instance.newDepositSerialID)
        else:
            instance_new = ''

        total = 0.0
        for i in all_in:
            total = total + i.amount
        context = {
            'instance': instance,
            'items': items,
            'total': total,
            'instance_new': instance_new
        }

        return render(request, 'home/depositDetail.html', context)
    else:
        return redirect('homeApp:loginPage')



@is_activated()
def edit_deposit_detail(request, id=None):
    if request.user.is_authenticated:
        instance = get_object_or_404(Deposit, id=int(id))
        items = DepositItem.objects.filter(depositID_id=instance.pk)
        interests = Interest.objects.filter(depositID_id=instance.pk, isDeleted=False)
        context = {
            'instance': instance,
            'items': items,
            'interests': interests
        }

        return render(request, 'home/editDepositDetail.html', context)
    else:
        return redirect('homeApp:loginPage')

@is_activated()
def download_backup(request, id=None):
    if request.user.is_authenticated:
        response = HttpResponse(content_type='text/json')
        response['Content-Disposition'] = 'attachment; filename="NextBillBackUp-{}.json"'.format(datetime.today())
        stdout_orig = sys.stdout
        sys.stdout = response
        management.call_command('dumpdata')
        sys.stdout = stdout_orig
        response.write(sys.stdout)
        return response
    else:
        return redirect('homeApp:loginPage')



def daily_report(request):
    if request.user.is_authenticated:
        try:
            opening = CashBook.objects.filter(datetime__lt=datetime.today().date(), isDeleted__exact=False).last()
            o_balance = opening.availableBalance
        except:
            o_balance = 0.0
        try:
            current = CashBook.objects.all().last()
            c = current.availableBalance
        except:
            c = 0.0

        total_c = 0.0
        total_d = 0.0

        for cre in CashBook.objects.filter(datetime__icontains=datetime.today().date(), isDeleted__exact=False,transactionType__icontains='Credit'):
            total_c = total_c + cre.interest + cre.amount

        for d in CashBook.objects.filter(datetime__icontains=datetime.today().date(), isDeleted__exact=False,transactionType__icontains='Debit'):
            total_d = total_d + d.interest + d.amount

        context = {
            'o_balance': o_balance,
            'c': c,
            'date': datetime.today().date(),
            'credit':total_c,
            'debit':total_d,
            'available_balance': total_c - total_d

        }

        return render(request, 'home/dailyReport.html', context)
    else:
        return redirect('homeApp:loginPage')


def print_billA5(request, *args, **kwargs):
    query = request.GET.get('q')

    depo = Deposit.objects.get(pk=int(query))
    depo_list = DepositItem.objects.filter(depositID_id=int(query))

    context = {
        'left': 3 - depo_list.count(),
        'loo': str().zfill(3- depo_list.count() - 1),
        'TotalInWords': num2words(int(depo.totalAmount)),
        'depo': depo,
        'depo_list': depo_list

    }
    return render(request, 'home/PrintA5.html', context)


def print_billA4(request, *args, **kwargs):
    query = request.GET.get('q')

    depo = Deposit.objects.get(pk=int(query))
    depo_list = DepositItem.objects.filter(depositID_id=int(query))

    context = {
        'left': 10 - depo_list.count(),
        'loo': str().zfill(10 - depo_list.count() - 1),
        'TotalInWords': num2words(int(depo.totalAmount)),
        'depo': depo,
        'depo_list': depo_list

    }
    return render(request, 'home/PrintA4.html', context)


def with_print_billA5(request, *args, **kwargs):
    query = request.GET.get('q')

    depo = Deposit.objects.get(pk=int(query))
    depo_list = DepositItem.objects.filter(depositID_id=int(query), isDeleted__exact=False)
    int_list = Interest.objects.filter(depositID_id=int(query), isDeleted__exact=False)
    int_total = 0.0
    for i in int_list:
        int_total = int_total + i.amount

    try:
        a_paid = num2words(int(depo.totalAmountPaid))
    except:
        a_paid = 'Zero'

    try:
        a_paid_interest = num2words(int(int_total))
    except:
        a_paid_interest = 'Zero'

    context = {
        'left': 2 - depo_list.count(),
        'loo': str().zfill(2 - depo_list.count() - 1),
        'TotalInWords': a_paid,
        'depo': depo,
        'depo_list': depo_list,
        'a_paid_interest':a_paid_interest,
        'int_total':int_total,
        'int_list':int_list



    }
    return render(request, 'home/WithPrintA5.html', context)


def with_print_billA4(request, *args, **kwargs):
    query = request.GET.get('q')

    depo = Deposit.objects.get(pk=int(query))
    depo_list = DepositItem.objects.filter(depositID_id=int(query), isDeleted__exact=False)
    int_list = Interest.objects.filter(depositID_id=int(query), isDeleted__exact=False)
    int_total = 0.0
    for i in int_list:
        int_total = int_total + i.amount
    try:
        a_paid = num2words(int(depo.totalAmountPaid))
    except:
        a_paid = 'Zero'

    try:
        a_paid_interest = num2words(int(int_total))
    except:
        a_paid_interest = 'Zero'

    context = {
        'left': 2 - depo_list.count(),
        'loo': str().zfill(2 - depo_list.count() - 1),
        'TotalInWords': a_paid,
        'depo': depo,
        'depo_list': depo_list,
        'a_paid_interest':a_paid_interest,
        'int_total':int_total,
        'int_list':int_list



    }
    return render(request, 'home/WithPrintA4.html', context)


@is_activated()
def customers_list(request):
    if request.user.is_authenticated:
        return render(request, 'home/customers.html')
    else:
        return redirect('homeApp:loginPage')

home/templates/home/dashboard.html
{% load static %}
{% load pwa %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
    {% progressive_web_app_meta %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="{% static 'logo/512.png' %}" type="image/gif" sizes="16x16">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/semantic.min.css' %}">
    <script src="{% static 'js/semantic.min.js' %}"></script>
    <script src="{% static 'sw/app.js' %}"></script>
    <style>
        .bg-custom {
            background: rgb(255, 255, 255);
            background: linear-gradient(180deg, rgba(255, 255, 255, 1) 60%, rgba(241, 255, 0, 1) 100%, rgba(0, 212, 255, 1) 100%);
        }
    </style>
</head>
<body class="bg-custom">

<div class="ui vertically divided grid inverted" style="text-align: center">
    <div class="one column row">
        <div class="column">
            <p style="text-transform: uppercase;
    font-size: 25px;
    font-weight: bold;
    color: rgba(0, 0, 0, 0.7);
    font-family: monospace;
    padding-top: 10px;
    padding-bottom: 0px;
    text-shadow: 2px 8px 6px rgba(0,0,0,0.2),
                 0px -5px 35px rgba(255,255,255,0.3);
    margin-bottom: 0;"
            >A Management Software<span style="font-size: 12px">  (V 1.2.0) </span></p>
            <img src="{% static 'logo/512.png' %}" alt="" width="80" height="80">

            <p style="color:grey;font-family: serif;font-style: italic;">"By Ziva Infotech"</p>
        </div>
    </div>
    <div class="four column row">

        <div class="column ">
            <a href="{% url 'homeApp:new_deposit' %}">
                <p><i class="download icon" style="font-size: 5rem;"></i><br>NEW DEPOSIT </p>
            </a>
        </div>
        <div class="column">
            <a href="{% url 'homeApp:deposit_history' %}">
                <p><i class="history icon" style="font-size: 5rem;"></i><br>DEPOSIT HISTORY </p>
            </a>
        </div>
        <div class="column">
            <a href="{% url 'homeApp:customers_list' %}">
                <p><i class="user icon" style="font-size: 5rem;"></i><br>CUSTOMERS </p>
            </a>
        </div>
        <div class="column">
            <a href="{% url 'homeApp:logout' %}">
                <p><i class="share square icon" style="font-size: 5rem;"></i><br>LOGOUT </p>
            </a>
        </div>

    </div>
    <div class="three column row">

        <div class="column">
            <a href="{% url 'homeApp:daily_report' %}">
                <p><i class="hand holding usd icon
" style="font-size: 5rem;"></i><br>CASH BOOK</p>
            </a>
        </div>
        <div class="column">
            <div class="ui blue raised segment">
                <h4>Quick Search By Serial No.</h4>
                <div class="ui fluid short search action input" id="highlightexample">
                    <input autocomplete="false" autofocus class="prompt" id="search" placeholder="Search..."
                           type="text">
                    <div class="results"></div>
                    <div class="ui buttons">
                        <button onclick="SearchDeposit()" class="ui green button">Search</button>
                        <div class="or"></div>
                        <button class="ui red button" onclick="clearBtn()">Clear</button>
                    </div>
                </div>

            </div>
        </div>
        <div class="column">
            <a href="{% url 'homeApp:backup' %}">
                <p><i class="hdd outline icon" style="font-size: 5rem;"></i><br>BACKUP </p>
            </a>
        </div>

    </div>

    <div class="three column row">

        <div class="column">

        </div>

        <div class="column">

        </div>

    </div>

</div>
<div class="ui error message" style="height: 60px;width: 50%;margin: 0 auto;">
    <i class="close icon"></i>
    <div class="header">
        ZIVAINFOTECH Reminder!
    </div>
    {{ message }}
</div>
<script>
    $('.message .close')
        .on('click', function () {
            $(this)
                .closest('.message')
                .transition('fade')
            ;
        })
    ;


    function SearchDeposit() {
        var search = $('#search').val();
        var formdata = new FormData();
        formdata.append('Search', search);
        $.ajax({
            url: "{% url 'homeApp:search_deposit' %}",
            type: "post",
            data: formdata,
            contentType: false,
            cache: false,
            processData: false,

            success: function (response) {
                if (response.message === 'success') {
                    $('body')
                        .toast({
                            class: 'success',
                            message: 'Deposit Detail Found.'
                        })
                    ;
                    window.location.href = "/deposit_detail/" + response.id + "/";

                } else {
                    $('body')
                        .toast({
                            class: 'warning',
                            message: 'No Deposit Detail Found ! Please try again.'
                        })
                    ;

                }

                return response;
            },
            error: function () {
                $('body')
                    .toast({
                        class: 'error',
                        message: 'An error occurred !'
                    })
                ;
            }
        });

    }

    function clearBtn() {
        $('#search').val('');

    }

    $(document).ready(function () {

        $('#search').keydown(function (event) {
            // enter has keyCode = 13, change it if you want to use another button
            if (event.keyCode == 13) {
                SearchDeposit();
                return false;
            }
        });

    });
</script>
<script>


    $('#highlightexample').search({
    type: 'standard',
    minCharacters: 3,
    apiSettings: {
        url: '/api/get_deposits_search/',
        beforeSend: function(settings) {
            settings.data.query = settings.urlData.query;
            return settings;
        },
        onResponse: function(apiResponse) {
            var response = {
                results: []
            };

            // Transform API response to Fomantic UI format
            $.each(apiResponse, function(index, item) {
                response.results.push({
                    title: item.depositID,  // Adjust based on your API response
                    description: item.name + ' - ' + item.statusID+ ' - ' + item.depositDate // Optional: if you want to show additional info
                });
            });
            return response;
        }
    },
    fields: {
        results: 'results',
        title: 'title',
        description: 'description'  // Optional
    },
    onSelect: function(result, response) {
        // Handle selection
        console.log('Selected:', result.title);
    }
});
</script>
</body>
</html>

home/templates/home/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
            <link rel="icon" href="{% static 'logo/512.png' %}" type="image/gif" sizes="16x16">
         <script src="{% static 'js/jquery.min.js' %}"></script>
      <script src="{% static 'js/semantic.min.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/semantic.min.css' %}">


    <title>Login</title>

<style>
    body{
          background-color: #ACAFB8;
    }
     fieldset {
    border: none;
  }
    .container{
        padding-top: 100px;
    }
     .ui.grid {
        display: flex;
        justify-content: center;
    }
      header {
    background-color: #202731;
    color: #C5C6C8;
    display: block;
    padding: 1.5em;
    text-align: center;
          font-size: 16px;
  }
    .input-wrapper {
      position: relative;
      display: block;
      margin: 2em auto;
      border-bottom: 1px solid #FC7148;
      border-radius: 3px;
      width: 300px;
      padding-left: 20px;
      font-size: 20px;
  }
   input {
        width: 100%;
        line-height: 2;
        background-color: transparent;
        border: none;
        padding: .6em .5em;
        outline: 0;
       color: white;
    }

    .column_1{
        width: 300px;
        height: 400px;
        background-color: #fcffe0;

    }
    .column_2{
         width: 300px;
        height: 400px;
        background-color: #272E38;
    }

     button {
      outline: 0;
      font-size: 12px;
      letter-spacing: 0.1em;
      background-color: #FC7148;
      color: #fff;
      border: none;
      border-radius: 3px;
      width: 200px;
      padding: 1.2em 0;
      margin: 4em auto;
      display: block;
      border-top: 2px solid transparent;
      border-bottom: 2px solid transparent;
  }
    hover {
      border-bottom-color:darkgoldenrod;
    }

     p.hd{
        text-align: center;
        font-variant: small-caps;
        font-weight: bold;
        font-family: "Times New Roman", Times, serif;
        font-size: 30px;
        color: #e4d533;
    }
    .credit{
        text-align: center;
        font-size: 18px;
        padding-top: 20px;
    }
</style>
</head>
<body>
    <div class="container">
        <div class="ui equal width center aligned padded grid">
            <div class="ui raised segment" style="background-color: #DCDCDC; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19)">
              <div class="ui two column centered grid">
                <div class="column_1" style="width: 350px; padding: 05px">
                    <img class="ui centered medium circular image" src="{% static 'logo/512.png' %}" style="width: 150px;height: 150px;margin-top: 30px">
                    <br>
                    <p class="hd">SHIROI STORE</p>
                </div>
                <div class="column_2" style="width: 350px; padding: 05px">
                    <form id="userLoginForm" action="{% url 'homeApp:postLogin' %}" method="post">{% csrf_token %}
                    <div  class="login-form-container" >
                        <header>LOGIN</header>
                    <fieldset>
                        <div class="input-wrapper">
                            <input type="text" placeholder="Username" name="userName"  id="userName" />
                        </div>
                        <div class="input-wrapper">
                            <input type="password" placeholder="Password " name="password"  id="password"/>
                        </div>
                        <button style="cursor: pointer" id="continue" type="button" onclick="UserLogin()">CONTINUE</button>
                    </fieldset>
                    </div>
                        </form>
                </div>
              </div>
            </div>
        </div>
    </div>
<p class="credit" style="margin-top: 50px;">Developed by <a href="http://www.zivainfotech.com" target="_blank">Ziva Infotech</a></p>
    <script>
         function UserLogin() {
        var username = $('#userName').val();
        var password = $('#password').val();

        if(username===""||password===""){


              $('body')
                            .toast({
                                class: 'error',
                                message: 'Username and Password is required !'
                            })
                        ;

            }
            else{
            data = new FormData();
                data.append('userName', username);
                data.append('password', password);

                 $.ajax({
                    type: 'post',
                    url: '{% url 'homeApp:postLogin' %}',
                    data: data,
                    contentType: false,
                    cache: false,
                    processData: false,


                    success: function (response) {
                        if (response.message === 'success') {
                            $('body')
                                .toast({
                                    class: 'success',
                                    message: 'Login Successful.'
                                });
                          document.location.href = "{% url 'homeApp:dashboard' %}"
                        }
                        else {
                            $('body')
                                .toast({
                                    class: 'warning',
                                    message: 'Incorrect username or password. Please try again.'
                                })
                            ;

                        }

                        return response;
                    },
                    error: function () {
                        $('body')
                            .toast({
                                class: 'error',
                                message: 'An error occurred !'
                            })
                        ;
                    }
                });
            }
    }
    </script>
</body>
</html>